### ISSUE TITLE
Accessing the firmware

### ISSUE THREAD

**Issue by heshananupama** [viktorradnai/bluepilljs#1]
Is there a firmware file linked in the repository that I could use rather than installing everything and compiling by my own. It would be great if you could point out to a place where the firmware file is located. Thanks

**Comment by viktorradnai** [comment]
Hi, thanks for your interest in trying BluepillJS. Currently this is my personal project which I'm using with a home built one axis joystick (aircraft rudder pedals). 

Unless you have the exact same requirement, it's almost inevitable that you will need to change the source code and recompile. There are no options to change the number of joystick axes, that is set [here](https://github.com/viktorradnai/bluepilljs/blob/master/usbcfg.c#L60). If you are using a sensor other than an LSM303C then you will need to uncomment the one you need and comment what you don't need [here](https://github.com/viktorradnai/bluepilljs/blob/master/main.c#L67). You also need to figure out how you want to use the magnetic sensor data. I am using the X and Y values to calculate a heading value. If you need to use the X and Y values separately (eg because you have a joystick with the magnet set on the bottom end of the stick and the sensor beneath it) then you need to change the code for that [here](https://github.com/viktorradnai/bluepilljs/blob/master/joystick.c#L156) (or further down in the same file if using a different sensor).

All of this tweaking means that a precompiled firmware would (I think) not work for most people. But if you are OK with the LSM303C and one joystick axis then let me know and I'm happy make it availabe.

**Comment by heshananupama** [comment]
Thank you very much for the message. Frankly, I needed few firmwares related to ARM architecture for my research work and I got yours as one. I tried to manually run the makefile but it ended up with some errors and I think it's related to ChibiOS. It would be great if I could access the firmware rather than trying to have set up. Thanks for your time

**Comment by viktorradnai** [comment]
I've made a release for you, hope you find it useful. https://github.com/viktorradnai/bluepilljs/releases/tag/v0.1.0

The build was only tested with ChibiOS 17.6.4 and may not work with other versions. Hope this helps.

**Comment by heshananupama** [comment]
Thank you @viktorradnai :)
